# Test Functionality of GestionOt{class}

In [ ]:

from eerssa import gestionOT
from eerssa import matrizActividades
from pprint import pprint
from pathlib import Path
import pandas as pd

test_path = '/home/vlad/GIT/eerssa_gh/ordenes_de_trabajo/tests/ot_test/'
list_pdfs = []
for path in Path( test_path ).glob("**/*.pdf"):
  list_pdfs.append( str(path) )
  list_pdfs.sort()

obj_lists = []
obj_data  = []
for file in list_pdfs:
  ot = gestionOT.GestionOt( file )
  ot.load_ot()
  obj_lists.append( ot )
  obj_data.append( ot.data )

  ot_as_pd = pd.DataFrame( obj_data )

matriz_test = matrizActividades.ConvertirOT_a_ActividadesCSV(  obj_lists[3] )

Success!!!

AttributeError: 'list' object has no attribute 'iloc'

In [3]:
matriz_test = matrizActividades.ConvertirOT_a_ActividadesCSV(  obj_lists[3] )

In [4]:
matriz_test[['Item','Evento','Actividad','InicioEvento','Dia','Fecha']]

,Item,Evento,Actividad,InicioEvento,Dia,Fecha
0,1,En Bodega Yacuambi se coordina trabajos con lo...,PROG,2024-07-29 08:00:00,lunes,2024-07-29 00:00:00
1,2,En Yacuambi sector del Estadio Municipal se re...,NO PROG,2024-07-29 08:30:00,lunes,2024-07-29 00:00:00
2,3,DAÑO REPORTADO POR CC. Mensaje de CC. Traslado...,TRANSP,2024-07-29 09:10:00,lunes,2024-07-29 00:00:00
3,4,"En Tamboloma, Est 175924 se encuentra tirafusi...",NO PROG,2024-07-29 10:00:00,lunes,2024-07-29 00:00:00
5,6,DAÑO REPORTADO POR CC. Mensaje de CC. Traslado...,TRANSP,2024-07-29 10:40:00,lunes,2024-07-29 00:00:00
6,7,"En Huacapamba, Est 193856 se encuentra tirafus...",NO PROG,2024-07-29 12:20:00,lunes,2024-07-29 00:00:00
8,9,LUNCH en Yacuambi,ALIMEN,2024-07-29 14:00:00,lunes,2024-07-29 00:00:00
9,10,DAÑO REPORTADO POR CC. Mensaje de CC. Traslado...,TRANSP,2024-07-29 15:00:00,lunes,2024-07-29 00:00:00
10,11,"En Jembuentza, Est 31161 se encuentra tirafusi...",NO PROG,2024-07-29 15:45:00,lunes,2024-07-29 00:00:00
12,13,DAÑO REPORTADO POR CC. Mensaje de CC. Traslado...,TRANSP,2024-07-29 16:30:00,lunes,2024-07-29 00:00:00
13,14,En Piuntza de Guadalupe por informacion de CC ...,NO PROG,2024-07-29 17:00:00,lunes,2024-07-29 00:00:00
14,15,DAÑO REPORTADO POR CC. Mensaje de CC. Traslado...,TRANSP,2024-07-29 18:00:00,lunes,2024-07-29 00:00:00
15,16,En Yacuambi en la Est 31116 se encuentra tiraf...,NO PROG,2024-07-29 19:20:00,lunes,2024-07-29 00:00:00
18,19,Se retorna a Bodega,TRANSP,2024-07-29 20:30:00,lunes,2024-07-29 00:00:00
19,20,"SE LABORA: NL, JP, SE y LC de 08:00 a 14:00 y ...",LABORA,2024-07-29 00:00:01,lunes,2024-07-29 00:00:00

In [29]:
dbg = ot_as_pd.iloc[3]
dbg['actividades']

[{'Item': '1',
  'Actividad': 'PROG',
  'Evento': 'En Bodega Yacuambi se coordina trabajos con los compañeros,\nlegalización de OT, se revisa herramientas y materiales,',
  'Ali': None,
  'Alimentador': None,
  'Tipo': 'RUTINARIA',
  'InicioEvento': '2024-07-29 08:00:00',
  'FinEvento': '2024-07-29 08:30:00'},
 {'Item': '2',
  'Actividad': 'NO PROG',
  'Evento': 'En Yacuambi sector del Estadio Municipal se retira acometida\nprovicionalmente del Med 1000376278 a pedido del cliente por\ncontruccion de nueva vivienda',
  'Ali': 'ALI',
  'Alimentador': 'Yacuambi',
  'Tipo': 'PREDICTIVO',
  'InicioEvento': '2024-07-29 08:30:00',
  'FinEvento': '2024-07-29 09:10:00'},
 {'Item': '3',
  'Actividad': 'TRANSP',
  'Evento': 'DAÑO REPORTADO POR CC. Mensaje de CC. Traslado desde Yacuambi hasta\nTamboloma informan derivacion a La Florida sin servicio eléctrico',
  'Ali': None,
  'Alimentador': None,
  'Tipo': 'TRANSPORTE',
  'InicioEvento': '2024-07-29 09:10:00',
  'FinEvento': '2024-07-29 10:00:00'},
 {'Item': '4',
  'Actividad': 'NO PROG',
  'Evento': 'En Tamboloma, Est 175924 se encuentra tirafusible quemado derivación\na La Florida, se revisa, se toma medidas de seguridad, se procede a\nreponer tirafusible de 15A-T y se normaliza el servicio electr',
  'Ali': 'ALI',
  'Alimentador': 'Yacuambi',
  'Tipo': 'CORRECTIVO',
  'InicioEvento': '2024-07-29 10:00:00',
  'FinEvento': '2024-07-29 10:40:00'},
 {'Item': '5',
  'Actividad': None,
  'Evento': 'CARGA: 35KVA ; FUSIBLE 1x15A -T\nFECHA DESC: 29/07/2024 (05:00 aprox)\nFECHA CONX: (10:40) CAUSA: invierno',
  'Ali': None,
  'Alimentador': None,
  'Tipo': None,
  'InicioEvento': None,
  'FinEvento': None},
 {'Item': '6',
  'Actividad': 'TRANSP',
  'Evento': 'DAÑO REPORTADO POR CC. Mensaje de CC. Traslado desde Tamboloma hasta\nEl Salado y luego a pie a Huacapamba informan derivacion a Las Playas\nsin servicio eléctrico',
  'Ali': None,
  'Alimentador': None,
  'Tipo': 'TRANSPORTE',
  'InicioEvento': '2024-07-29 10:40:00',
  'FinEvento': '2024-07-29 12:20:00'},
 {'Item': '7',
  'Actividad': 'NO PROG',
  'Evento': 'En Huacapamba, Est 193856 se encuentra tirafusible quemado derivación\na Playas, se revisa, se toma las medidas de seguridad, se procede a\nreponer tirafusible de 15A-T y se normaliza el servicio elect',
  'Ali': 'ALI',
  'Alimentador': 'Yacuambi',
  'Tipo': 'CORRECTIVO',
  'InicioEvento': '2024-07-29 12:20:00',
  'FinEvento': '2024-07-29 14:00:00'},
 {'Item': '8',
  'Actividad': None,
  'Evento': 'CARGA: 91KVA ; FUSIBLE 1x15A -T\nFECHA DESC: 29/07/2024 (05:00 aprox)\nFECHA CONX: (13:00) CAUSA: invierno',
  'Ali': None,
  'Alimentador': None,
  'Tipo': None,
  'InicioEvento': None,
  'FinEvento': None},
 {'Item': '9',
  'Actividad': 'ALIMEN',
  'Evento': 'LUNCH en Yacuambi',
  'Ali': None,
  'Alimentador': None,
  'Tipo': 'ALIMENTACI',
  'InicioEvento': '2024-07-29 14:00:00',
  'FinEvento': '2024-07-29 15:00:00'},
 {'Item': '10',
  'Actividad': 'TRANSP',
  'Evento': 'DAÑO REPORTADO POR CC. Mensaje de CC. Traslado desde Yacuambi hasta\nJembuentza informan derivacion a Nuevo Porvenir sin servicio\neléctrico',
  'Ali': None,
  'Alimentador': None,
  'Tipo': 'TRANSPORTE',
  'InicioEvento': '2024-07-29 15:00:00',
  'FinEvento': '2024-07-29 15:45:00'},
 {'Item': '11',
  'Actividad': 'NO PROG',
  'Evento': 'En Jembuentza, Est 31161 se encuentra tirafusible quemado derivación\na Nuevo Porvenir, se revisa, se toma las medidas de seguridad, se\nprocede a reponer tirafusible de 25A-K y se normaliza el servici',
  'Ali': 'ALI',
  'Alimentador': 'Yacuambi',
  'Tipo': 'CORRECTIVO',
  'InicioEvento': '2024-07-29 15:45:00',
  'FinEvento': '2024-07-29 16:30:00'},
 {'Item': '12',
  'Actividad': None,
  'Evento': 'CARGA: 70KVA ; FUSIBLE 1x25A -K\nFECHA DESC: 29/07/2024 (13:00 aprox)\nFECHA CONX: (16:30) CAUSA: invierno',
  'Ali': None,
  'Alimentador': None,
  'Tipo': None,
  'InicioEvento': None,
  'FinEvento': None},
 {'Item': '13',
  'Actividad': 'TRANSP',
  'Evento': 'DAÑO REPORTADO POR CC. Mensaje de CC. Traslado desde Jembuentza hasta\nPiuntza de Guadalupe informan luminaria de 100wNa que no enciende',
  'Ali': None,
  'Alimentador': None,
  'Tipo': 'TRANSPORTE',
  'InicioEvento': '2024-07-29 16:30:00',
  'FinEvento': '2024-07-29 17:00:00'},
 {'Item': '14',
  'Actividad': 'NO PROG',
  'Evento': 'En Piuntza de Guadalupe por informacion de CC en la Est 38749 se\nrevisa luminaria de 100wNa que no enciende, se revisa y la falla\npersisite y por falta de material queda pendiente el arreglo',
  'Ali': 'ALI',
  'Alimentador': 'Yacuambi',
  'Tipo': 'PREDICTIVO',
  'InicioEvento': '2024-07-29 17:00:00',
  'FinEvento': '2024-07-29 18:00:00'},
 {'Item': '15',
  'Actividad': 'TRANSP',
  'Evento': 'DAÑO REPORTADO POR CC. Mensaje de CC. Traslado desde Piuntza de\nGuadalupe hasta Yacuambi informan derivacion a San Jose Chico sin\nservicio eléctrico',
  'Ali': None,
  'Alimentador': None,
  'Tipo': 'TRANSPORTE',
  'InicioEvento': '2024-07-29 18:00:00',
  'FinEvento': '2024-07-29 19:20:00'},
 {'Item': '16',
  'Actividad': 'NO PROG',
  'Evento': 'En Yacuambi en la Est 31116 se encuentra tirafusible quemado\nderivación a San José Chico, se revisa y se encuentra ramas de\narboles chocando en la LMT, se toma',
  'Ali': 'ALI',
  'Alimentador': 'Yacuambi',
  'Tipo': 'CORRECTIVO',
  'InicioEvento': '2024-07-29 19:20:00',
  'FinEvento': '2024-07-29 20:30:00'},
 {'Item': '17',
  'Actividad': None,
  'Evento': 'Medidas de seguridad,se corta ramas de árboles y se despeja las linea\nluego se procede a reponer tirafusible de 6A-T y se normaliza el\nservicio eléctrico',
  'Ali': None,
  'Alimentador': None,
  'Tipo': None,
  'InicioEvento': None,
  'FinEvento': None},
 {'Item': '18',
  'Actividad': None,
  'Evento': 'CARGA: 5KVA ; FUSIBLE 1x6A -T\nFECHA DESC: 29/07/2024 (15:00 aprox)\nFECHA CONX: (20:30) CAUSA: vegetacion',
  'Ali': None,
  'Alimentador': None,
  'Tipo': None,
  'InicioEvento': None,
  'FinEvento': None},
 {'Item': '19',
  'Actividad': 'TRANSP',
  'Evento': 'Se retorna a Bodega',
  'Ali': None,
  'Alimentador': None,
  'Tipo': 'TRANSPORTE',
  'InicioEvento': '2024-07-29 20:30:00',
  'FinEvento': '2024-07-29 20:40:00'},
 {'Item': '20',
  'Actividad': None,
  'Evento': 'SE LABORA: NL, JP, SE y LC de 08:00 a 14:00 y de 15:00 a 20:40',
  'Ali': None,
  'Alimentador': None,
  'Tipo': None,
  'InicioEvento': None,
  'FinEvento': None},
 {'Item': '21',
  'Actividad': None,
  'Evento': 'MATERIALES UTILIZADOS: 1 tirafusible de 6A-T, 1 tirafusibles de 15A-T,\n1 tirafusible de 25A-T y 1 tirafusible de 15A-K',
  'Ali': None,
  'Alimentador': None,
  'Tipo': None,
  'InicioEvento': None,
  'FinEvento': None}]

In [30]:
actividades = pd.DataFrame(dbg['actividades'])
etiq_labora = actividades.query( 'Actividad.isnull()', engine = 'python' )
etiq_labora

,Item,Actividad,Evento,Ali,Alimentador,Tipo,InicioEvento,FinEvento
4,5,None,CARGA: 35KVA ; FUSIBLE 1x15A -T\nFECHA DESC: 2...,None,None,None,None,None
7,8,None,CARGA: 91KVA ; FUSIBLE 1x15A -T\nFECHA DESC: 2...,None,None,None,None,None
11,12,None,CARGA: 70KVA ; FUSIBLE 1x25A -K\nFECHA DESC: 2...,None,None,None,None,None
16,17,None,"Medidas de seguridad,se corta ramas de árboles...",None,None,None,None,None
17,18,None,CARGA: 5KVA ; FUSIBLE 1x6A -T\nFECHA DESC: 29/...,None,None,None,None,None
19,20,None,"SE LABORA: NL, JP, SE y LC de 08:00 a 14:00 y ...",None,None,None,None,None
20,21,None,"MATERIALES UTILIZADOS: 1 tirafusible de 6A-T, ...",None,None,None,None,None

In [31]:
#  |SE LAB___  // mayusculas o minusculas
etiq_SE_LABORA = etiq_labora.Evento.str.contains('^se lab', case = False, regex = True )
index_labora = etiq_SE_LABORA[etiq_SE_LABORA].index.values
fechaModa = '16/09/1988'

In [32]:
for fila in index_labora:
  actividades.at[fila,'Actividad'] = 'LABORA'
  actividades.at[fila,'InicioEvento'] = fechaModa + " 00:00:01"
  actividades.at[fila,'FinEvento'] = fechaModa + " 00:00:02"

In [33]:
actividades

,Item,Actividad,Evento,Ali,Alimentador,Tipo,InicioEvento,FinEvento
0,1,PROG,En Bodega Yacuambi se coordina trabajos con lo...,None,None,RUTINARIA,2024-07-29 08:00:00,2024-07-29 08:30:00
1,2,NO PROG,En Yacuambi sector del Estadio Municipal se re...,ALI,Yacuambi,PREDICTIVO,2024-07-29 08:30:00,2024-07-29 09:10:00
2,3,TRANSP,DAÑO REPORTADO POR CC. Mensaje de CC. Traslado...,None,None,TRANSPORTE,2024-07-29 09:10:00,2024-07-29 10:00:00
3,4,NO PROG,"En Tamboloma, Est 175924 se encuentra tirafusi...",ALI,Yacuambi,CORRECTIVO,2024-07-29 10:00:00,2024-07-29 10:40:00
4,5,None,CARGA: 35KVA ; FUSIBLE 1x15A -T\nFECHA DESC: 2...,None,None,None,None,None
5,6,TRANSP,DAÑO REPORTADO POR CC. Mensaje de CC. Traslado...,None,None,TRANSPORTE,2024-07-29 10:40:00,2024-07-29 12:20:00
6,7,NO PROG,"En Huacapamba, Est 193856 se encuentra tirafus...",ALI,Yacuambi,CORRECTIVO,2024-07-29 12:20:00,2024-07-29 14:00:00
7,8,None,CARGA: 91KVA ; FUSIBLE 1x15A -T\nFECHA DESC: 2...,None,None,None,None,None
8,9,ALIMEN,LUNCH en Yacuambi,None,None,ALIMENTACI,2024-07-29 14:00:00,2024-07-29 15:00:00
9,10,TRANSP,DAÑO REPORTADO POR CC. Mensaje de CC. Traslado...,None,None,TRANSPORTE,2024-07-29 15:00:00,2024-07-29 15:45:00
10,11,NO PROG,"En Jembuentza, Est 31161 se encuentra tirafusi...",ALI,Yacuambi,CORRECTIVO,2024-07-29 15:45:00,2024-07-29 16:30:00
11,12,None,CARGA: 70KVA ; FUSIBLE 1x25A -K\nFECHA DESC: 2...,None,None,None,None,None
12,13,TRANSP,DAÑO REPORTADO POR CC. Mensaje de CC. Traslado...,None,None,TRANSPORTE,2024-07-29 16:30:00,2024-07-29 17:00:00
13,14,NO PROG,En Piuntza de Guadalupe por informacion de CC ...,ALI,Yacuambi,PREDICTIVO,2024-07-29 17:00:00,2024-07-29 18:00:00
14,15,TRANSP,DAÑO REPORTADO POR CC. Mensaje de CC. Traslado...,None,None,TRANSPORTE,2024-07-29 18:00:00,2024-07-29 19:20:00
15,16,NO PROG,En Yacuambi en la Est 31116 se encuentra tiraf...,ALI,Yacuambi,CORRECTIVO,2024-07-29 19:20:00,2024-07-29 20:30:00
16,17,None,"Medidas de seguridad,se corta ramas de árboles...",None,None,None,None,None
17,18,None,CARGA: 5KVA ; FUSIBLE 1x6A -T\nFECHA DESC: 29/...,None,None,None,None,None
18,19,TRANSP,Se retorna a Bodega,None,None,TRANSPORTE,2024-07-29 20:30:00,2024-07-29 20:40:00
19,20,LABORA,"SE LABORA: NL, JP, SE y LC de 08:00 a 14:00 y ...",None,None,None,16/09/1988 00:00:01,16/09/1988 00:00:02
20,21,None,"MATERIALES UTILIZADOS: 1 tirafusible de 6A-T, ...",None,None,None,None,None

In [36]:
for iteraciones in range( actividades['InicioEvento'].isna().sum() ):
  fila = 1
  totalIdx = len(actividades.index)

  while fila < totalIdx:
    if( pd.isna(actividades.at[actividades.index[fila],'InicioEvento']) ):  # AND or OR ?
      data = actividades.at[ actividades.index[fila-1],'Evento' ]
      actividades.at[ actividades.index[fila-1],'Evento' ] = data + '\r' + actividades.at[ actividades.index[fila],'Evento' ]
      actividades = actividades.drop(actividades.index[fila])
      fila = totalIdx
    
    fila = fila + 1

    """ Lo programo de esta manera ya que al hacer el Drop no se actualizan los indices
      si uso un lazo FOR. Al hacerlo de esta manera cada vez leo los indices tomando
      en cuenta aquellos que ya elimine. y funciona.
    """

actividades.Item = actividades.Item.astype(int)

In [37]:
actividades

,Item,Actividad,Evento,Ali,Alimentador,Tipo,InicioEvento,FinEvento
0,1,PROG,En Bodega Yacuambi se coordina trabajos con lo...,None,None,RUTINARIA,2024-07-29 08:00:00,2024-07-29 08:30:00
1,2,NO PROG,En Yacuambi sector del Estadio Municipal se re...,ALI,Yacuambi,PREDICTIVO,2024-07-29 08:30:00,2024-07-29 09:10:00
2,3,TRANSP,DAÑO REPORTADO POR CC. Mensaje de CC. Traslado...,None,None,TRANSPORTE,2024-07-29 09:10:00,2024-07-29 10:00:00
3,4,NO PROG,"En Tamboloma, Est 175924 se encuentra tirafusi...",ALI,Yacuambi,CORRECTIVO,2024-07-29 10:00:00,2024-07-29 10:40:00
5,6,TRANSP,DAÑO REPORTADO POR CC. Mensaje de CC. Traslado...,None,None,TRANSPORTE,2024-07-29 10:40:00,2024-07-29 12:20:00
6,7,NO PROG,"En Huacapamba, Est 193856 se encuentra tirafus...",ALI,Yacuambi,CORRECTIVO,2024-07-29 12:20:00,2024-07-29 14:00:00
8,9,ALIMEN,LUNCH en Yacuambi,None,None,ALIMENTACI,2024-07-29 14:00:00,2024-07-29 15:00:00
9,10,TRANSP,DAÑO REPORTADO POR CC. Mensaje de CC. Traslado...,None,None,TRANSPORTE,2024-07-29 15:00:00,2024-07-29 15:45:00
10,11,NO PROG,"En Jembuentza, Est 31161 se encuentra tirafusi...",ALI,Yacuambi,CORRECTIVO,2024-07-29 15:45:00,2024-07-29 16:30:00
12,13,TRANSP,DAÑO REPORTADO POR CC. Mensaje de CC. Traslado...,None,None,TRANSPORTE,2024-07-29 16:30:00,2024-07-29 17:00:00
13,14,NO PROG,En Piuntza de Guadalupe por informacion de CC ...,ALI,Yacuambi,PREDICTIVO,2024-07-29 17:00:00,2024-07-29 18:00:00
14,15,TRANSP,DAÑO REPORTADO POR CC. Mensaje de CC. Traslado...,None,None,TRANSPORTE,2024-07-29 18:00:00,2024-07-29 19:20:00
15,16,NO PROG,En Yacuambi en la Est 31116 se encuentra tiraf...,ALI,Yacuambi,CORRECTIVO,2024-07-29 19:20:00,2024-07-29 20:30:00
18,19,TRANSP,Se retorna a Bodega,None,None,TRANSPORTE,2024-07-29 20:30:00,2024-07-29 20:40:00
19,20,LABORA,"SE LABORA: NL, JP, SE y LC de 08:00 a 14:00 y ...",None,None,None,16/09/1988 00:00:01,16/09/1988 00:00:02

In [1]:
from eerssa import gestionOT
from eerssa import matrizActividades
from pprint import pprint
from pathlib import Path
import pandas as pd

Success!!!

[nltk_data] Error loading stopwords: <urlopen error [Errno -2] Name or
[nltk_data]     service not known>
[nltk_data] Error loading punkt: <urlopen error [Errno -2] Name or
[nltk_data]     service not known>

## Probar solo un archivo

In [2]:
ot_test = gestionOT.GestionOt('/home/vlad/GIT/eerssa_gh/ordenes_de_trabajo/tests/ot_test/12_NL_Tres_hojas_ultima_vacia.pdf')

In [3]:
ot_test.load_ot()

ot_test.data

{'version': '0.12.0',
 'link': '/home/vlad/GIT/eerssa_gh/ordenes_de_trabajo/tests/ot_test/12_NL_Tres_hojas_ultima_vacia.pdf',
 'id_ot': 134508,
 'exito': True,
 'cuadrilla': 'Yacuambi Z1 (Cuadrilla. Nro. 8)',
 'responsable': ['LOZANO SIGCHO NAUN ENRIQUE', 'JECE'],
 'colaboradores': {'total': 3,
  'nombres': [['CABRERA GONZALEZ LUIS RENE', 'LNI1'],
   ['ERAS POMA SANTOS FERNANDO', 'LNI1'],
   ['PUCHAICELA CASTILLO JORGE ALEXANDER', 'LIN1']]},
 'diaSemana': 'lunes',
 'fecha': datetime.datetime(2024, 7, 29, 0, 0, tzinfo=<DstTzInfo 'America/Guayaquil' -05-1 day, 19:00:00 STD>),
 'fechaInicio': 'lunes, 29 de julio del 2024',
 'sitio': 'Yacuambi - Tamboloma, Hucapamba y Jembuentza',
 'descripcion': 'Traslado a Tamboloma para revisar sector sin servicio eléctrico derivación a La Florida luego a Huacapamba\nrevisar derivación a Playas sin servicio eléctrico. Atender daños por llamado de Centro de  Control',
 'tEstimado': '8',
 'vehiculo': {'numero': 'R-171',
  'placa': 'AAA-4278',
  'marca': 'CAMIONETA CHEVROLET DMAX CRDI PREMIER AC BLANCO',
  'rentado': 'SI',
  'propietario': 'NESTORIO  ELISEO MOROCHO RAMON',
  'chofer': 'NESTORIO  ELISEO MOROCHO RAMON'},
 'kmInicial': 16518,
 'kmFinal': 16678,
 'kmRecorrido': 160,
 'trabajo': ['A - SIN VOLTAJE',
  'TRABAJO EN ALTURA - BAJO NIVEL',
  'CON ENERGÍA/VOLTAJE - BAJO VOLTAJE',
  'TRABAJO EN ALTURA - SOBRE NIVEL',
  'CON ENERGÍA/VOLTAJE - MEDIO VOLTAJE'],
 'riesgos': {'BIOLÓGICOS': ['Virus',
   'Infección por presencia de hongos',
   'Usar mascarillas y alcohol'],
  'ELÉCTRICOS': ['Electrización (Paso energ. x cuerp',
   'Electrocución o electrización',
   'Usar epp'],
  'MECÁNICOS': ['Caída de objetos',
   'Golpes en extremidades y/o cuerpo',
   'Usar epp'],
  'PSICOSOCIALES': ['Realciones sociales',
   'Estrés',
   'Distanciamiento social']},
 'seguridad': {'Herramientas Manuales Adecuadas': 'BUENO',
  'Identificada Área de Seguridad': 'BUENO',
  'Medio de transporte': 'BUENO'},
 'epps': {'A. Protección para la Cabeza (Casco con barbiquejo)': 'BUENO',
  'D. Protección Respiratoria (Mascarilla, respiradores)': 'BUENO',
  'E. Ropa de Trabajo (Uniforme entragado por EERSSA)': 'BUENO',
  'G. Protección manos (Guantes de acuerdo nivel voltaje)': 'BUENO',
  'I. Protección extremidades inferiores (Calzado dieléctrico': 'BUENO',
  'L. Equipo de posicionamiento (Cinturón seguridad)': 'BUENO'},
 'precauciones': 'Cumplir con el reglamento de trabajo de la EERSSA. Cumplir con las 5 reglas de oro',
 'carencias': '',
 'accidente': 'NO',
 'observaciones': '',
 'numeracion': 179,
 'gerencia': 'OPERACIÓN Y MANTENIMIENTO',
 'estado': 'TERMINADO',
 'firmas': ['LOZANO SIGCHO NAUN ENRIQUE',
  'PALACIOS MERINO ERNESTO VLADIMIR',
  'MARQUEZ APOLO JHONNY FABIAN'],
 'actividades': [{'Item': '1',
   'Actividad': 'PROG',
   'Descipcion': 'En Bodega Yacuambi se coordina trabajos con los compañeros,\nlegalización de OT, se revisa herramientas y materiales,',
   'Ali': '·',
   'Alimentador': '·',
   'Tipo': 'RUTINARIA',
   'FechaInicial': '2024-07-29 08:00:00',
   'FechaFinal': '2024-07-29 08:30:00'},
  {'Item': '2',
   'Actividad': 'NO PROG',
   'Descipcion': 'En Yacuambi sector del Estadio Municipal se retira acometida\nprovicionalmente del Med 1000376278 a pedido del cliente por\ncontruccion de nueva vivienda',
   'Ali': 'ALI',
   'Alimentador': 'Yacuambi',
   'Tipo': 'PREDICTIVO',
   'FechaInicial': '2024-07-29 08:30:00',
   'FechaFinal': '2024-07-29 09:10:00'},
  {'Item': '3',
   'Actividad': 'TRANSP',
   'Descipcion': 'DAÑO REPORTADO POR CC. Mensaje de CC. Traslado desde Yacuambi hasta\nTamboloma informan derivacion a La Florida sin servicio eléctrico',
   'Ali': '·',
   'Alimentador': '·',
   'Tipo': 'TRANSPORTE',
   'FechaInicial': '2024-07-29 09:10:00',
   'FechaFinal': '2024-07-29 10:00:00'},
  {'Item': '4',
   'Actividad': 'NO PROG',
   'Descipcion': 'En Tamboloma, Est 175924 se encuentra tirafusible quemado derivación\na La Florida, se revisa, se toma medidas de seguridad, se procede a\nreponer tirafusible de 15A-T y se normaliza el servicio electr',
   'Ali': 'ALI',
   'Alimentador': 'Yacuambi',
   'Tipo': 'CORRECTIVO',
   'FechaInicial': '2024-07-29 10:00:00',
   'FechaFinal': '2024-07-29 10:40:00'},
  {'Item': '5',
   'Actividad': '·',
   'Descipcion': 'CARGA: 35KVA ; FUSIBLE 1x15A -T\nFECHA DESC: 29/07/2024 (05:00 aprox)\nFECHA CONX: (10:40) CAUSA: invierno',
   'Ali': '·',
   'Alimentador': '·',
   'Tipo': '·',
   'FechaInicial': '·',
   'FechaFinal': '·'},
  {'Item': '6',
   'Actividad': 'TRANSP',
   'Descipcion': 'DAÑO REPORTADO POR CC. Mensaje de CC. Traslado desde Tamboloma hasta\nEl Salado y luego a pie a Huacapamba informan derivacion a Las Playas\nsin servicio eléctrico',
   'Ali': '·',
   'Alimentador': '·',
   'Tipo': 'TRANSPORTE',
   'FechaInicial': '2024-07-29 10:40:00',
   'FechaFinal': '2024-07-29 12:20:00'},
  {'Item': '7',
   'Actividad': 'NO PROG',
   'Descipcion': 'En Huacapamba, Est 193856 se encuentra tirafusible quemado derivación\na Playas, se revisa, se toma las medidas de seguridad, se procede a\nreponer tirafusible de 15A-T y se normaliza el servicio elect',
   'Ali': 'ALI',
   'Alimentador': 'Yacuambi',
   'Tipo': 'CORRECTIVO',
   'FechaInicial': '2024-07-29 12:20:00',
   'FechaFinal': '2024-07-29 14:00:00'},
  {'Item': '8',
   'Actividad': '·',
   'Descipcion': 'CARGA: 91KVA ; FUSIBLE 1x15A -T\nFECHA DESC: 29/07/2024 (05:00 aprox)\nFECHA CONX: (13:00) CAUSA: invierno',
   'Ali': '·',
   'Alimentador': '·',
   'Tipo': '·',
   'FechaInicial': '·',
   'FechaFinal': '·'},
  {'Item': '9',
   'Actividad': 'ALIMEN',
   'Descipcion': 'LUNCH en Yacuambi',
   'Ali': '·',
   'Alimentador': '·',
   'Tipo': 'ALIMENTACI',
   'FechaInicial': '2024-07-29 14:00:00',
   'FechaFinal': '2024-07-29 15:00:00'},
  {'Item': '10',
   'Actividad': 'TRANSP',
   'Descipcion': 'DAÑO REPORTADO POR CC. Mensaje de CC. Traslado desde Yacuambi hasta\nJembuentza informan derivacion a Nuevo Porvenir sin servicio\neléctrico',
   'Ali': '·',
   'Alimentador': '·',
   'Tipo': 'TRANSPORTE',
   'FechaInicial': '2024-07-29 15:00:00',
   'FechaFinal': '2024-07-29 15:45:00'},
  {'Item': '11',
   'Actividad': 'NO PROG',
   'Descipcion': 'En Jembuentza, Est 31161 se encuentra tirafusible quemado derivación\na Nuevo Porvenir, se revisa, se toma las medidas de seguridad, se\nprocede a reponer tirafusible de 25A-K y se normaliza el servici',
   'Ali': 'ALI',
   'Alimentador': 'Yacuambi',
   'Tipo': 'CORRECTIVO',
   'FechaInicial': '2024-07-29 15:45:00',
   'FechaFinal': '2024-07-29 16:30:00'},
  {'Item': '12',
   'Actividad': '·',
   'Descipcion': 'CARGA: 70KVA ; FUSIBLE 1x25A -K\nFECHA DESC: 29/07/2024 (13:00 aprox)\nFECHA CONX: (16:30) CAUSA: invierno',
   'Ali': '·',
   'Alimentador': '·',
   'Tipo': '·',
   'FechaInicial': '·',
   'FechaFinal': '·'},
  {'Item': '13',
   'Actividad': 'TRANSP',
   'Descipcion': 'DAÑO REPORTADO POR CC. Mensaje de CC. Traslado desde Jembuentza hasta\nPiuntza de Guadalupe informan luminaria de 100wNa que no enciende',
   'Ali': '·',
   'Alimentador': '·',
   'Tipo': 'TRANSPORTE',
   'FechaInicial': '2024-07-29 16:30:00',
   'FechaFinal': '2024-07-29 17:00:00'},
  {'Item': '14',
   'Actividad': 'NO PROG',
   'Descipcion': 'En Piuntza de Guadalupe por informacion de CC en la Est 38749 se\nrevisa luminaria de 100wNa que no enciende, se revisa y la falla\npersisite y por falta de material queda pendiente el arreglo',
   'Ali': 'ALI',
   'Alimentador': 'Yacuambi',
   'Tipo': 'PREDICTIVO',
   'FechaInicial': '2024-07-29 17:00:00',
   'FechaFinal': '2024-07-29 18:00:00'},
  {'Item': '15',
   'Actividad': 'TRANSP',
   'Descipcion': 'DAÑO REPORTADO POR CC. Mensaje de CC. Traslado desde Piuntza de\nGuadalupe hasta Yacuambi informan derivacion a San Jose Chico sin\nservicio eléctrico',
   'Ali': '·',
   'Alimentador': '·',
   'Tipo': 'TRANSPORTE',
   'FechaInicial': '2024-07-29 18:00:00',
   'FechaFinal': '2024-07-29 19:20:00'},
  {'Item': '16',
   'Actividad': 'NO PROG',
   'Descipcion': 'En Yacuambi en la Est 31116 se encuentra tirafusible quemado\nderivación a San José Chico, se revisa y se encuentra ramas de\narboles chocando en la LMT, se toma',
   'Ali': 'ALI',
   'Alimentador': 'Yacuambi',
   'Tipo': 'CORRECTIVO',
   'FechaInicial': '2024-07-29 19:20:00',
   'FechaFinal': '2024-07-29 20:30:00'},
  {'Item': '17',
   'Actividad': '·',
   'Descipcion': 'Medidas de seguridad,se corta ramas de árboles y se despeja las linea\nluego se procede a reponer tirafusible de 6A-T y se normaliza el\nservicio eléctrico',
   'Ali': '·',
   'Alimentador': '·',
   'Tipo': '·',
   'FechaInicial': '·',
   'FechaFinal': '·'},
  {'Item': '18',
   'Actividad': '·',
   'Descipcion': 'CARGA: 5KVA ; FUSIBLE 1x6A -T\nFECHA DESC: 29/07/2024 (15:00 aprox)\nFECHA CONX: (20:30) CAUSA: vegetacion',
   'Ali': '·',
   'Alimentador': '·',
   'Tipo': '·',
   'FechaInicial': '·',
   'FechaFinal': '·'},
  {'Item': '19',
   'Actividad': 'TRANSP',
   'Descipcion': 'Se retorna a Bodega',
   'Ali': '·',
   'Alimentador': '·',
   'Tipo': 'TRANSPORTE',
   'FechaInicial': '2024-07-29 20:30:00',
   'FechaFinal': '2024-07-29 20:40:00'},
  {'Item': '20',
   'Actividad': '·',
   'Descipcion': 'SE LABORA: NL, JP, SE y LC de 08:00 a 14:00 y de 15:00 a 20:40',
   'Ali': '·',
   'Alimentador': '·',
   'Tipo': '·',
   'FechaInicial': '·',
   'FechaFinal': '·'},
  {'Item': '21',
   'Actividad': '·',
   'Descipcion': 'MATERIALES UTILIZADOS: 1 tirafusible de 6A-T, 1 tirafusibles de 15A-T,\n1 tirafusible de 25A-T y 1 tirafusible de 15A-K',
   'Ali': '·',
   'Alimentador': '·',
   'Tipo': '·',
   'FechaInicial': '·',
   'FechaFinal': '·'},
  []],
 'n_fallas': 0,
 'n_errores': 0,
 'n_revisar': 0,
 'n_info': 1}

In [4]:
ot_test.log

[{'t': '2025-01-16T18:51:58.724919',
  'level': 'INFO',
  'message': 'Creacion de la OT',
  'detail': 'Ninguno'}]

## Test dierctory

In [3]:
from dask.distributed import LocalCluster
client = LocalCluster().get_client()

In [2]:
test_path = '/home/vlad/GIT/eerssa_gh/ordenes_de_trabajo/tests/ot_test/'
list_pdfs = []
for path in Path( test_path ).glob("**/*.pdf"):
  list_pdfs.append( str(path) )
  list_pdfs.sort()
len(list_pdfs)

29

In [7]:
## ¿Como se usa DASK para creacion de objetos?

ots_raw = []
for file in list_pdfs:
  this_ot = client.submit( gestionOT.GestionOt, file )
  conversion = client.submit( gestionOT.GestionOt, file )

In [3]:
obj_lists = []
obj_data  = []
for file in list_pdfs:
  ot = gestionOT.GestionOt( file )
  ot.load_ot()
  obj_lists.append( ot )
  obj_data.append( ot.data )

In [5]:
len(obj_data)

29

In [4]:
obj_lists[3].log

[{'t': '2025-01-17T03:49:16.915439',
  'level': 'INFO',
  'message': 'Creacion de la OT',
  'detail': 'Ninguno'}]

In [4]:
ot_as_pd = pd.DataFrame( obj_data )

In [ ]:
matriz_test = matrizActividades.ConvertirOT_a_ActividadesCSV(  ot_as_pd.iloc[3] )

In [6]:
matriz_test

,uuid,Item,Confianza,Cuenta,Evento,Alimentador,Primario,Tipo,Actividad,Cuadrilla,...,HorasExtra,Desconexion,SIG,Responsable,Colaboradores,Vehiculo,Sitio,Dia,id_ot,Archivo
0,8bfba9fe-b02a-4db4-bf41-5319f58bbd3c,1,0.0,·,En Bodega Yacuambi se coordina trabajos con lo...,·,False,RUTINARIA,PROG,Yacuambi Z1 (Cuadrilla. Nro. 8),...,False,False,No,LOZANO SIGCHO NAUN ENRIQUE,total;nombres,R-171,"Yacuambi - Tamboloma, Hucapamba y Jembuentza",·,134508.0,12_NL_Tres_hojas_ultima_vacia.pdf
1,20e6076b-3705-408a-b755-a82a15df4a9f,2,0.0,·,En Yacuambi sector del Estadio Municipal se re...,Yacuambi,False,PREDICTIVO,NO PROG,Yacuambi Z1 (Cuadrilla. Nro. 8),...,False,False,No,LOZANO SIGCHO NAUN ENRIQUE,total;nombres,R-171,"Yacuambi - Tamboloma, Hucapamba y Jembuentza",·,134508.0,12_NL_Tres_hojas_ultima_vacia.pdf
2,63127a0e-4e65-41b5-8c37-575895feda09,3,0.0,·,DAÑO REPORTADO POR CC. Mensaje de CC. Traslado...,·,False,TRANSPORTE,TRANSP,Yacuambi Z1 (Cuadrilla. Nro. 8),...,False,False,No,LOZANO SIGCHO NAUN ENRIQUE,total;nombres,R-171,"Yacuambi - Tamboloma, Hucapamba y Jembuentza",·,134508.0,12_NL_Tres_hojas_ultima_vacia.pdf
3,b782cff2-6f30-4009-92d7-fd6e59d4076c,4,0.0,·,"En Tamboloma, Est 175924 se encuentra tirafusi...",Yacuambi,False,CORRECTIVO,NO PROG,Yacuambi Z1 (Cuadrilla. Nro. 8),...,False,False,No,LOZANO SIGCHO NAUN ENRIQUE,total;nombres,R-171,"Yacuambi - Tamboloma, Hucapamba y Jembuentza",·,134508.0,12_NL_Tres_hojas_ultima_vacia.pdf
4,7533c937-9dd4-4c07-a807-d41b192ce6e8,5,0.0,·,CARGA: 35KVA ; FUSIBLE 1x15A -T\nFECHA DESC: 2...,·,False,·,·,Yacuambi Z1 (Cuadrilla. Nro. 8),...,False,False,No,LOZANO SIGCHO NAUN ENRIQUE,total;nombres,R-171,"Yacuambi - Tamboloma, Hucapamba y Jembuentza",·,134508.0,12_NL_Tres_hojas_ultima_vacia.pdf
5,e1d9aaed-ca5c-4743-a06a-82c3a77c975c,6,0.0,·,DAÑO REPORTADO POR CC. Mensaje de CC. Traslado...,·,False,TRANSPORTE,TRANSP,Yacuambi Z1 (Cuadrilla. Nro. 8),...,False,False,No,LOZANO SIGCHO NAUN ENRIQUE,total;nombres,R-171,"Yacuambi - Tamboloma, Hucapamba y Jembuentza",·,134508.0,12_NL_Tres_hojas_ultima_vacia.pdf
6,d38871b3-6e69-4cbd-936f-e0f5878354b9,7,0.0,·,"En Huacapamba, Est 193856 se encuentra tirafus...",Yacuambi,False,CORRECTIVO,NO PROG,Yacuambi Z1 (Cuadrilla. Nro. 8),...,False,False,No,LOZANO SIGCHO NAUN ENRIQUE,total;nombres,R-171,"Yacuambi - Tamboloma, Hucapamba y Jembuentza",·,134508.0,12_NL_Tres_hojas_ultima_vacia.pdf
7,89caaff7-b86d-42ce-90d3-d3c903dfc64a,8,0.0,·,CARGA: 91KVA ; FUSIBLE 1x15A -T\nFECHA DESC: 2...,·,False,·,·,Yacuambi Z1 (Cuadrilla. Nro. 8),...,False,False,No,LOZANO SIGCHO NAUN ENRIQUE,total;nombres,R-171,"Yacuambi - Tamboloma, Hucapamba y Jembuentza",·,134508.0,12_NL_Tres_hojas_ultima_vacia.pdf
8,c56fcbda-dbbf-4824-814b-e35ed3559c81,9,0.0,·,LUNCH en Yacuambi,·,False,ALIMENTACI,ALIMEN,Yacuambi Z1 (Cuadrilla. Nro. 8),...,False,False,No,LOZANO SIGCHO NAUN ENRIQUE,total;nombres,R-171,"Yacuambi - Tamboloma, Hucapamba y Jembuentza",·,134508.0,12_NL_Tres_hojas_ultima_vacia.pdf
9,da1d4b7e-bd9b-4b62-a4dd-423a4fff1d97,10,0.0,·,DAÑO REPORTADO POR CC. Mensaje de CC. Traslado...,·,False,TRANSPORTE,TRANSP,Yacuambi Z1 (Cuadrilla. Nro. 8),...,False,False,No,LOZANO SIGCHO NAUN ENRIQUE,total;nombres,R-171,"Yacuambi - Tamboloma, Hucapamba y Jembuentza",·,134508.0,12_NL_Tres_hojas_ultima_vacia.pdf
10,e0d80eca-9b7b-4f95-a45a-c96313fc1081,11,0.0,·,"En Jembuentza, Est 31161 se encuentra tirafusi...",Yacuambi,False,CORRECTIVO,NO PROG,Yacuambi Z1 (Cuadrilla. Nro. 8),...,False,False,No,LOZANO SIGCHO NAUN ENRIQUE,total;nombres,R-171,"Yacuambi - Tamboloma, Hucapamba y Jembuentza",·,134508.0,12_NL_Tres_hojas_ultima_vacia.pdf
11,6d876ab0-b9ec-46d6-a1b2-2aead4c05e5b,12,0.0,·,CARGA: 70KVA ; FUSIBLE 1x25A -K\nFECHA DESC: 2...,·,False,·,·,Yacuambi Z1 (Cuadrilla. Nro. 8),...,False,False,No,LOZANO SIGCHO NAUN ENRIQUE,total;nombres,R-171,"Yacuambi - Tamboloma, Hucapamba y Jembuentza",·,134508.0,12_NL_Tres_hojas_ultima_vacia.pdf
12,75054cad-8721-4927-84b5-4311bb034d81,13,0.0,·,DAÑO REPORTADO POR CC. Mensaje de CC. Traslado...,·,False,TRANSPORTE,TRANSP,Yacuambi Z1 (Cuadrilla. Nro. 8),...,False,False,No,LOZANO SIGCHO NAUN ENRIQUE,total;nombres,R-171,"Yacuambi - Tamboloma, Hucapamba y Jembuentza",·,134508.0,12_NL_Tres_hojas_ultima_vacia.pdf
13,27ba5dd6-4af7-48ca-885b-8e299a3d6ab0,14,0.0,·,En Piuntza de Guadalupe por informacion de CC ...,Yacuambi,False,PREDICTIVO,NO PROG,Yacuambi Z1 (Cuadrilla. Nro. 8),...,False,False,No,LOZANO SIGCHO NAUN ENRIQUE,total;nombres,R-171,"Yacuambi - Tamboloma, Hucapamba y Jembuentza",·,134508.0,12_NL_Tres_hojas_ultima_vacia.pdf
14,6860df3c-0dd6-4eee-a93e-32a3cad1bde2,15,0.0,·,DAÑO REPORTADO POR CC. Mensaje de CC. Traslado...,·,False,TRANSPORTE,TRANSP,Yacuambi Z1 (Cuadrilla. Nro. 8),...,False,False,No,LOZANO SIGCHO NAUN ENRIQUE,total;nombres,R-171,"Yacuambi - Tamboloma, Hucapamba y Jembuentza",·,134508.0,12_NL_Tres_hojas_ultima_vacia.pdf
15,9726e126-a221-453c-a13a-22104296c652,16,0.0,·,En Yacuambi en la Est 31116 se encuentra tiraf...,Yacuambi,False,CORRECTIVO,NO PROG,Yacuambi Z1 (Cuadrilla. Nro. 8),...,False,False,No,LOZANO SIGCHO NAUN ENRIQUE,total;nombres,R-171,"Yacuambi - Tamboloma, Hucapamba y Jembuentza",·,134508.0,12_NL_Tres_hojas_ultima_vacia.pdf
16,a1ad8830-541e-4c01-bf21-50ffa524a19a,17,0.0,·,"Medidas de seguridad,se corta ramas de árboles...",·,False,·,·,Yacuambi Z1 (Cuadrilla. Nro. 8),...,False,False,No,LOZANO SIGCHO NAUN ENRIQUE,total;nombres,R-171,"Yacuambi - Tamboloma, Hucapamba y Jembuentza",·,134508.0,12_NL_Tres_hojas_ultima_vacia.pdf
17,1f9104ba-6165-492b-82ef-60579e37c8ef,18,0.0,·,CARGA: 5KVA ; FUSIBLE 1x6A -T\nFECHA DESC: 29/...,·,False,·,·,Yacuambi Z1 (Cuadrilla. Nro. 8),...,False,False,No,LOZANO SIGCHO NAUN ENRIQUE,total;nombres,R-171,"Yacuambi - Tamboloma, Hucapamba y Jembuentza",·,134508.0,12_NL_Tres_hojas_ultima_vacia.pdf
18,49fcb47c-0460-42c0-8741-2d2b38497018,19,0.0,·,Se retorna a Bodega,·,False,TRANSPORTE,TRANSP,Yacuambi Z1 (Cuadrilla. Nro. 8),...,False,False,No,LOZANO SIGCHO NAUN ENRIQUE,total;nombres,R-171,"Yacuambi - Tamboloma, Hucapamba y Jembuentza",·,134508.0,12_NL_Tres_hojas_ultima_vacia.pdf
19,2b849e53-1ebb-4e06-a400-aa64b036033c,20,0.0,·,"SE LABORA: NL, JP, SE y LC de 08:00 a 14:00 y ...",·,False,·,·,Yacuambi Z1 (Cuadrilla. Nro. 8),...,False,False,No,LOZANO SIGCHO NAUN ENRIQUE,total;nombres,R-171,"Yacuambi - Tamboloma, Hucapamba y Jembuentza",·,134508.0,12_NL_Tres_hojas_ultima_vacia.pdf
20,3d1738ba-8a57-4b6b-847a-207ee4223b9a,21,0.0,·,"MATERIALES UTILIZADOS: 1 tirafusible de 6A-T, ...",·,False,·,·,Yacuambi Z1 (Cuadrilla. Nro. 8),...,False,False,No,LOZANO SIGCHO NAUN ENRIQUE,total;nombres,R-171,"Yacuambi - Tamboloma, Hucapamba y Jembuentza",·,134508.0,12_NL_Tres_hojas_ultima_vacia.pdf

In [8]:
dbg = ot_as_pd.iloc[3]
matrizActividades.organizarActividades( dbg )

,index,Item,Actividad,Evento,Ali,Alimentador,Tipo,InicioEvento,FinEvento
0,0,1,PROG,En Bodega Yacuambi se coordina trabajos con lo...,·,·,RUTINARIA,2024-07-29 08:00:00,2024-07-29 08:30:00
1,1,2,NO PROG,En Yacuambi sector del Estadio Municipal se re...,ALI,Yacuambi,PREDICTIVO,2024-07-29 08:30:00,2024-07-29 09:10:00
2,2,3,TRANSP,DAÑO REPORTADO POR CC. Mensaje de CC. Traslado...,·,·,TRANSPORTE,2024-07-29 09:10:00,2024-07-29 10:00:00
3,3,4,NO PROG,"En Tamboloma, Est 175924 se encuentra tirafusi...",ALI,Yacuambi,CORRECTIVO,2024-07-29 10:00:00,2024-07-29 10:40:00
4,4,5,·,CARGA: 35KVA ; FUSIBLE 1x15A -T\nFECHA DESC: 2...,·,·,·,·,·
5,5,6,TRANSP,DAÑO REPORTADO POR CC. Mensaje de CC. Traslado...,·,·,TRANSPORTE,2024-07-29 10:40:00,2024-07-29 12:20:00
6,6,7,NO PROG,"En Huacapamba, Est 193856 se encuentra tirafus...",ALI,Yacuambi,CORRECTIVO,2024-07-29 12:20:00,2024-07-29 14:00:00
7,7,8,·,CARGA: 91KVA ; FUSIBLE 1x15A -T\nFECHA DESC: 2...,·,·,·,·,·
8,8,9,ALIMEN,LUNCH en Yacuambi,·,·,ALIMENTACI,2024-07-29 14:00:00,2024-07-29 15:00:00
9,9,10,TRANSP,DAÑO REPORTADO POR CC. Mensaje de CC. Traslado...,·,·,TRANSPORTE,2024-07-29 15:00:00,2024-07-29 15:45:00
10,10,11,NO PROG,"En Jembuentza, Est 31161 se encuentra tirafusi...",ALI,Yacuambi,CORRECTIVO,2024-07-29 15:45:00,2024-07-29 16:30:00
11,11,12,·,CARGA: 70KVA ; FUSIBLE 1x25A -K\nFECHA DESC: 2...,·,·,·,·,·
12,12,13,TRANSP,DAÑO REPORTADO POR CC. Mensaje de CC. Traslado...,·,·,TRANSPORTE,2024-07-29 16:30:00,2024-07-29 17:00:00
13,13,14,NO PROG,En Piuntza de Guadalupe por informacion de CC ...,ALI,Yacuambi,PREDICTIVO,2024-07-29 17:00:00,2024-07-29 18:00:00
14,14,15,TRANSP,DAÑO REPORTADO POR CC. Mensaje de CC. Traslado...,·,·,TRANSPORTE,2024-07-29 18:00:00,2024-07-29 19:20:00
15,15,16,NO PROG,En Yacuambi en la Est 31116 se encuentra tiraf...,ALI,Yacuambi,CORRECTIVO,2024-07-29 19:20:00,2024-07-29 20:30:00
16,16,17,·,"Medidas de seguridad,se corta ramas de árboles...",·,·,·,·,·
17,17,18,·,CARGA: 5KVA ; FUSIBLE 1x6A -T\nFECHA DESC: 29/...,·,·,·,·,·
18,18,19,TRANSP,Se retorna a Bodega,·,·,TRANSPORTE,2024-07-29 20:30:00,2024-07-29 20:40:00
19,19,20,·,"SE LABORA: NL, JP, SE y LC de 08:00 a 14:00 y ...",·,·,·,·,·
20,20,21,·,"MATERIALES UTILIZADOS: 1 tirafusible de 6A-T, ...",·,·,·,·,·

In [15]:
aactiv = dbg['actividades']
#aactiv = aactiv[aactiv.Descripcion.notnull()]

In [10]:
pd.DataFrame(dbg['actividades'])

,Item,Actividad,Descipcion,Ali,Alimentador,Tipo,FechaInicial,FechaFinal
0,1,PROG,En Bodega Yacuambi se coordina trabajos con lo...,·,·,RUTINARIA,2024-07-29 08:00:00,2024-07-29 08:30:00
1,2,NO PROG,En Yacuambi sector del Estadio Municipal se re...,ALI,Yacuambi,PREDICTIVO,2024-07-29 08:30:00,2024-07-29 09:10:00
2,3,TRANSP,DAÑO REPORTADO POR CC. Mensaje de CC. Traslado...,·,·,TRANSPORTE,2024-07-29 09:10:00,2024-07-29 10:00:00
3,4,NO PROG,"En Tamboloma, Est 175924 se encuentra tirafusi...",ALI,Yacuambi,CORRECTIVO,2024-07-29 10:00:00,2024-07-29 10:40:00
4,5,·,CARGA: 35KVA ; FUSIBLE 1x15A -T\nFECHA DESC: 2...,·,·,·,·,·
5,6,TRANSP,DAÑO REPORTADO POR CC. Mensaje de CC. Traslado...,·,·,TRANSPORTE,2024-07-29 10:40:00,2024-07-29 12:20:00
6,7,NO PROG,"En Huacapamba, Est 193856 se encuentra tirafus...",ALI,Yacuambi,CORRECTIVO,2024-07-29 12:20:00,2024-07-29 14:00:00
7,8,·,CARGA: 91KVA ; FUSIBLE 1x15A -T\nFECHA DESC: 2...,·,·,·,·,·
8,9,ALIMEN,LUNCH en Yacuambi,·,·,ALIMENTACI,2024-07-29 14:00:00,2024-07-29 15:00:00
9,10,TRANSP,DAÑO REPORTADO POR CC. Mensaje de CC. Traslado...,·,·,TRANSPORTE,2024-07-29 15:00:00,2024-07-29 15:45:00
10,11,NO PROG,"En Jembuentza, Est 31161 se encuentra tirafusi...",ALI,Yacuambi,CORRECTIVO,2024-07-29 15:45:00,2024-07-29 16:30:00
11,12,·,CARGA: 70KVA ; FUSIBLE 1x25A -K\nFECHA DESC: 2...,·,·,·,·,·
12,13,TRANSP,DAÑO REPORTADO POR CC. Mensaje de CC. Traslado...,·,·,TRANSPORTE,2024-07-29 16:30:00,2024-07-29 17:00:00
13,14,NO PROG,En Piuntza de Guadalupe por informacion de CC ...,ALI,Yacuambi,PREDICTIVO,2024-07-29 17:00:00,2024-07-29 18:00:00
14,15,TRANSP,DAÑO REPORTADO POR CC. Mensaje de CC. Traslado...,·,·,TRANSPORTE,2024-07-29 18:00:00,2024-07-29 19:20:00
15,16,NO PROG,En Yacuambi en la Est 31116 se encuentra tiraf...,ALI,Yacuambi,CORRECTIVO,2024-07-29 19:20:00,2024-07-29 20:30:00
16,17,·,"Medidas de seguridad,se corta ramas de árboles...",·,·,·,·,·
17,18,·,CARGA: 5KVA ; FUSIBLE 1x6A -T\nFECHA DESC: 29/...,·,·,·,·,·
18,19,TRANSP,Se retorna a Bodega,·,·,TRANSPORTE,2024-07-29 20:30:00,2024-07-29 20:40:00
19,20,·,"SE LABORA: NL, JP, SE y LC de 08:00 a 14:00 y ...",·,·,·,·,·
20,21,·,"MATERIALES UTILIZADOS: 1 tirafusible de 6A-T, ...",·,·,·,·,·

In [15]:
dbg

version                                                     0.12.0
link             /home/vlad/GIT/eerssa_gh/ordenes_de_trabajo/te...
id_ot                                                     134508.0
exito                                                         True
cuadrilla                          Yacuambi Z1 (Cuadrilla. Nro. 8)
responsable                     [LOZANO SIGCHO NAUN ENRIQUE, JECE]
colaboradores    {'total': 3, 'nombres': [['CABRERA GONZALEZ LU...
diaSemana                                                    lunes
fecha                                    2024-07-29 00:00:00-05:00
fechaInicio                            lunes, 29 de julio del 2024
fechaFinal                                     29/07/2024 20:40:00
sitio                 Yacuambi - Tamboloma, Hucapamba y Jembuentza
descripcion      Traslado a Tamboloma para revisar sector sin s...
tEstimado                                                        8
vehiculo         {'numero': 'R-171', 'placa': 'AAA-4278', 'marc...
kmInicial                                                  16518.0
kmFinal                                                    16678.0
kmRecorrido                                                  160.0
trabajo          [A - SIN VOLTAJE, TRABAJO EN ALTURA - BAJO NIV...
riesgos          {'BIOLÓGICOS': ['Virus', 'Infección por presen...
seguridad        {'Herramientas Manuales Adecuadas': 'BUENO', '...
epps             {'A. Protección para la Cabeza (Casco con barb...
precauciones     Cumplir con el reglamento de trabajo de la EER...
carencias
accidente                                                       NO
observaciones
numeracion                                                   179.0
gerencia                                 OPERACIÓN Y MANTENIMIENTO
estado                                                   TERMINADO
firmas           [LOZANO SIGCHO NAUN ENRIQUE, PALACIOS MERINO E...
actividades      [{'Item': '1', 'Actividad': 'PROG', 'Evento': ...
n_fallas                                                       0.0
n_errores                                                      0.0
n_revisar                                                      0.0
n_info                                                         1.0
Name: 3, dtype: object

In [13]:
longDay = dbg['fecha'].strftime('%Y-%m-%d %H:%M:%S')

In [14]:
longDay.split(' ')[0]

'2024-07-29'